.ifndef CONSTANTS_INC
CONSTANTS_INC = 1

GOLDEN_RAM = $400

LOCAL_WORK_AREA_GOLDEN_OFFSET = 514
PARAMETERS_WORK_AREA_GOLDEN_OFFSET = 1015

LOGIC_FILE_LOGIC_CODE_OFFSET = 2
LOGIC_FILE_LOGIC_BANK_OFFSET = 7

LOGIC_ENTRY_POINT_OFFSET = 1



.endif
